name: Continuous Integration
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci_vertification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          online_shopping_ms/customer/package-lock.json
          online_shopping_ms/products/package-lock.json
          online_shopping_ms/shopping/package-lock.json
          
    - name: Test Customer Service
      working-directory: ./online_shopping_ms/customer
      run: |
        npm ci
        npm test
        
    - name: Test Products Service
      working-directory: ./online_shopping_ms/products
      run: |
        npm ci
        npm test
        
    - name: Test Shopping Service
      working-directory: ./online_shopping_ms/shopping
      run: |
        npm ci
        npm test
